### ISSUE TITLE
public key not found

### ISSUE THREAD

**Issue by fbukevin** [PixelPin/PPIntegration#2]
I use my iPhone 6s (iOS 10.2.1) to run the project. With PPIntegration.h and libPPIntegration.a, the app can successfully install but still get trouble.

```
2017-02-06 23:52:34.662375 PixelPinSwift[4610:1375801] public key not found, is it in the bundle
2017-02-06 23:52:34.663914 PixelPinSwift[4610:1375801] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: object cannot be nil (key: v_Data)'
```

**Comment by lukos** [comment]
Hi Veck,

The documentation on our developer site is out of date. I should be
updating it over the next day to match the latest integration and mobile
app. I will let you know when it is updated.

Regards

Luke Briner

**Comment by fbukevin** [comment]
OK, thanks!

**Comment by lukos** [comment]
Hi Veck,

Updated documentation can now be found here: http://developer.pixelpin.io/

I will update the readme on github to make it clear that it is old code.

Thanks

Luke

**Comment by fbukevin** [comment]
Hi, Luke!

I got it. Some troubles of images there.

![default](https://cloud.githubusercontent.com/assets/4548874/22691231/763e5d3a-ed74-11e6-9669-3390068d7be7.PNG)

**Comment by lukos** [comment]
Thanks for that.

Case-sensitive images on linux! Fixed now.
